language: node_js
sudo: false
node_js:
  - 8
  - 10
install:
  - npm install
  - bower install
script:
  - pulp build && pulp test
cache:
  directories:
    - "node_modules"
    - "bower_components"
    - "output"
