language: node_js
sudo: false
node_js:
  - 6
install:
  - npm install
  - bower install
script:
  - travis_wait 30 pulp build && travis_wait pulp test
cache:
  directories:
    - "node_modules"
    - "bower_components"
    - "output"
