#!/usr/bin/env bash

case $1 in
  8)
    NODE_VERSION=8
    ;;
  10)
    NODE_VERSION=10
    ;;
  *)
    NODE_VERSION=6
esac

nix-build -A fhsEnv nixos/fhs-node-${NODE_VERSION}.nix && \
result/bin/fhs-node-$NODE_VERSION
